# Schema for the configuration files of the Domain module.

domain.domain.*:
  type: mapping
  label: 'Domain'
  mapping:
    uuid:
      type: string
      label: 'ID'
    domain_id:
      type: integer
      label: 'Domain ID'
    hostname:
      type: string
      label: 'Hostname'
    name:
      type: string
      label: 'Name'
    scheme:
      type: string
      label: 'Scheme'
    status:
      type: boolean
      label: 'Status'
    weight:
      type: integer
      label: 'Weight'
    is_default:
      type: boolean
      label: 'Default domain'
