services:
  domain_config.subscriber:
    class: Drupal\domain_config\EventSubscriber\DomainConfigSubscriber
    tags:
      - { name: event_subscriber }
    arguments: ['@domain.manager', '@config.factory', '@config.storage']
