services:
  domain.config_subscriber:
    class: Drupal\domain\EventSubscriber\ConfigSubscriber
    arguments: ['@domain.loader', '@domain_negotiator']
    tags:
      - { name: event_subscriber }
  domain.config_factory_override:
    class: Drupal\domain\Config\DomainConfigFactoryOverride
    arguments: ['@config.storage', '@event_dispatcher', '@config.typed']
    tags:
      - { name: config.factory.override, priority: -250 }
      - { name: event_subscriber }
